name: deploy flast app on self-hosted
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: docker install
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Deploy with docker compose
        run: docker-compose up -d --build