name: deploy flast app on self-hosted
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy app
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker and docker-compose if missing
        run: |
          if ! command -v docker.io &> /dev/null || ! command -v docker-compose &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y docker-compose
            sudo apt-get install -y docker.io
            sudo usermod -aG docker $USER
          else
            echo "Docker and docker-compose already installed."
          fi

      - name: Deploy with docker compose
        run: |
          sudo env DOCKER_USERNAME=$DOCKER_USERNAME docker-compose up -d --build --force-recreate