name: deploy flast app on kubernetes
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: self-hosted
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy with docker composer
        run: docker compose up -d --build