name: devsecops pipeline
on:
  workflow_dispatch:
jobs:
  
 code-quality:
    uses: ./.github/workflows/code-quality.yml

 secrets-scan:
    uses: ./.github/workflows/secrets-scan.yml

 dependency-scan:
    uses: ./.github/workflows/dependency-scan.yml

 docker-scan:
    uses: ./.github/workflows/docker-lint.yml

 image-scan:
    uses: ./.github/workflows/image-scan.yml

 deploy-to-server:
    uses: ./.github/workflows/deploy-to-server.yml