# Lint Docker Compose files
# Uses hadolint to lint the Dockerfile
name: docker lint
on:
  workflow_call:
jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Docker Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile